### ISSUE TITLE
Pre loading problem in website

### ISSUE THREAD

**Issue by SahityaRoy** [Eduhub-Community/Eduhub-Community.github.io#247]
The website is loading too much time to load on the server may be due to pre loader can you solve this problem?

**Comment by Rishav1707** [comment]
Shall I try?

**Comment by SahityaRoy** [comment]
Yup

**Comment by Rishav1707** [comment]
### The website is taking too much time to load because of these assets - 

![image](https://github.com/Eduhub-Community/Eduhub-Community.github.io/assets/97666287/8bad80c6-1a3d-40a6-8ecf-7db1ee1265d6)

### This data is given by https://pagespeed.web.dev/ website which is used to check the loading time or payload time of any website.

### I have set a property called `loading="lazy"` to all these assets that loads the required content only when needed which translates into reduced page load times.

**Comment by Rishav1707** [comment]
> ### The website is taking too much time to load because of these assets -
> ![image](https://user-images.githubusercontent.com/97666287/241686625-8bad80c6-1a3d-40a6-8ecf-7db1ee1265d6.png)
> 
> ### This data is given by https://pagespeed.web.dev/ website which is used to check the loading time or payload time of any website.
> ### I have set a property called `loading="lazy"` to all these assets that loads the required content only when needed which translates into reduced page load times.


Can I make a pull request?

**Comment by SahityaRoy** [comment]
What is the solution for this @Rishav1707

**Comment by Rishav1707** [comment]
> What is the solution for this @Rishav1707

I have set a property called loading="lazy" to all these assets that load the required content only when needed, which translates into reduced page load times.

**Comment by SahityaRoy** [comment]
remove the preloader as well and then create a PR

**Comment by Rishav1707** [comment]
> remove the preloader as well and then create a PR

Done👍🏻
