### ISSUE TITLE
Design a simple page for Code of Conduct 

### ISSUE THREAD

**Issue by neha030** [Eduhub-Community/Eduhub-Community.github.io#41]
![Screenshot (1178)](https://user-images.githubusercontent.com/72595335/194718268-dfe6482e-6209-477c-b8f0-041301033713.png)

**Comment by its-me-Harsh-Anand** [comment]
Hey @neha030 I want to work on this. Can you please assign me?

And what is to be written in code of conduct page? Can you give me some reference?

**Comment by neha030** [comment]
Go ahead with it. You will find a doc file linked to the code of conduct, just need to copy that content.

**Comment by shrutimeg** [comment]
@neha030 I want to work on these issue please assign  me these issue

**Comment by neha030** [comment]
> @neha030 I want to work on these issue please assign me these issue

This issue is already taken, you can definitely explore this project and raise new issues.

**Comment by SahityaRoy** [comment]
Any Update ???

**Comment by its-me-Harsh-Anand** [comment]
> Any Update ???
I've created a PR [https://github.com/Eduhub-Community/Eduhub-Community.github.io/pull/47#event-7549414630](https://github.com/Eduhub-Community/Eduhub-Community.github.io/pull/47#event-7549414630) which I had kept draft because only half of the work was done. But someone merged it.

Rest half work I'll do it today
